spring:
  ai:
    dashscope:
      api-key: sk-e273e9b0858c42ab85a8dd28bbdb7064
      chat:
        options:
          model: qwen3-max
gemini:
  api-key: sk-6B5pTuhUCABRfBdyP5UJOTarGDXzy97eQBQkdMWc18AvGwhw
  base-url: https://poloai.top/v1
  model: gemini-2.5-pro-thinking

search-api:
  api-key: A2j9FJa9powviQijXypZjAEw