spring:
  ai:
    dashscope:
      api-key: sk-e273e9b0858c42ab85a8dd28bbdb7064
      chat:
        options:
          model: qwen3-max
siliconflow:
  api-key: sk-xsozofrlbofcvbxabfpqcybqnhjmlzuztbxotnqyzurdzgaz
  base-url: https://api.siliconflow.cn/v1
  model: Qwen/Qwen3-VL-235B-A22B-Instruct


search-api:
  api-key: A2j9FJa9powviQijXypZjAEw